### ISSUE TITLE
French translation (demandetesdonnees.fr)

### ISSUE THREAD

**Issue by NathanBnm** [datenanfragen/website#199]
Now that the French version is online I made a few translation adjustments via Weblate. Please update the French translation.

I had a few comments to make.

First there are some pages that seem not to be fully translatable:
- https://www.demandetesdonnees.fr/suggest
- https://www.demandetesdonnees.fr/contact

The "Blog" page redirects to a 404 error in the French version (https://www.demandetesdonnees.fr/blog).

This page too (https://www.demandetesdonnees.fr/blog/your-gdpr-rights).

The "Datenafragen.de" name is displayed instead of "demandetesdonnees.fr" on the 404 page.

When editing a company, the description that appears when hovering elements seems not to be translatable too.

Don't hesitate to mention me for further info.

**Comment by baltpeter** [comment]
> Now that the French version is online I made a few translation adjustments via Weblate. Please update the French translation.

Thanks, will be done once #200 is merged which I will do once the tests have run.

> First there are some pages that seem not to be fully translatable:
> 
> * https://www.demandetesdonnees.fr/suggest
> * https://www.demandetesdonnees.fr/contact

These pages are translatable, not through Weblate though. They are simply Markdown files in [the content directory](https://github.com/datenanfragen/website/tree/master/content).  
As far as I understand, Weblate is intended for short strings rather than whole pages. If you have a better suggestion, I am very open to that, however!

> The "Blog" page redirects to a 404 error in the French version (https://www.demandetesdonnees.fr/blog).

That's because there are currently no blog posts in the French version. :D For now, #200 will just hide the 'Blog' link in the header.

> This page too (https://www.demandetesdonnees.fr/blog/your-gdpr-rights).

Same here. We don't have a translation for that.  
I guess we could change the links to point to the English version. Not great, though…

> The "Datenafragen.de" name is displayed instead of "demandetesdonnees.fr" on the 404 page.

You caught my laziness here. :D That was actually the case even for the English version. Will also be fixed by #200. 

> When editing a company, the description that appears when hovering elements seems not to be translatable too.

Yeah, that's also the case for the German version. The reason is that those strings are pulled directly from our [JSON schema](https://github.com/datenanfragen/data/blob/master/schema.json). So, the only way to translate them would be using the whole description text as the key which would be ugly and break as soon as the English translations change. :(

**Comment by NathanBnm** [comment]
Maybe I should translate the markdown files too?

**Comment by baltpeter** [comment]
If you're up for that, that would of course be great!

**Comment by NathanBnm** [comment]
@baltpeter if you want to creat a Frencg version of this image:

![image](https://user-images.githubusercontent.com/45366162/69012069-b91f1d80-0971-11ea-83ff-3dfbf75bcfd1.png)

You can use "Tu as le droit à la confidentialité."

**Comment by NathanBnm** [comment]
I'll replace `"featured_image": "/img/card/home-en.png"` by `"featured_image": "/img/card/home-fr.png"` in the `_index.fr.md` file.

**Comment by baltpeter** [comment]
Sounds good. There's also this one for the generator:

![](https://www.datarequests.org/img/card/generator-en.png)

**Comment by NathanBnm** [comment]
This would be "Génère facilement des demandes RGPD"

**Comment by NathanBnm** [comment]
> When editing a company, the description that appears when hovering elements seems not to be translatable too.

So the only left issue here seems to be that, but like you said:

> Yeah, that's also the case for the German version. The reason is that those strings are pulled directly from our [JSON schema](https://github.com/datenanfragen/data/blob/master/schema.json). So, the only way to translate them would be using the whole description text as the key which would be ugly and break as soon as the English translations change. :(

Will this translations often change? I don't think so, maybe it's better to user the whole string as a key than not translating anything. What do you think?

**Comment by baltpeter** [comment]
> maybe it's better to user the whole string as a key than not translating anything.

To be honest, I'm really not a fan of that idea. But let's patch in @zner0L, I guess.
