### ISSUE TITLE
Footer is missing on 404 page

### ISSUE THREAD

**Issue by NathanBnm** [datenanfragen/website#207]
I think it would be nice to keep it for more consistency and to guide the user if he is lost on the site.

**Comment by baltpeter** [comment]
I absolutely agree that it would be much better to have a footer on the 404 page. Unfortunately, not having it there wasn't a decision on our part rather than a necessary compromise to have a customized 404 page at all.

Basically, the problem is that we couldn't find a way to have Hugo generate the 404 page. Instead we can only have a single HTML file for all languages. See [this issue](https://git.my-server.in/datenanfragen/website/issues/115) in our old issue tracker for details.

**Comment by baltpeter** [comment]
I'll leave this issue open in case anyone has an idea on how to solve this problem.

**Comment by baltpeter** [comment]
Good news: We will soon be switching from Netlify to our own static site hosting solution (dattel, see #363). We should then be able to implement this.
