### ISSUE TITLE
'Fancy' link styling doesn't apply to all links

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#366]
The link selector @zner0L implemented a while back isn't sufficient to catch all links.

@mal-tee mentioned two cases in #365:

* The links to GitHub in https://www.datarequests.org/privacy#error-reports
* The links in the author box, e.g. to creativecommons.org in https://www.datarequests.org/blog/gdpr-territorial-scope#page-meta

**Comment by mal-tee** [comment]
https://github.com/datenanfragen/website/blob/62db845331fd935682ec4f2fb979463fe8f1e11c/assets/styles/framework.scss#L197-L200

This is the selector in question 😄

**Comment by botex98** [comment]
@mal-tee Hello, may I resolve this issue?
To be clear: what's the preferred outcome? That the links in the two cases are also caught by the selector?

**Comment by zner0L** [comment]
Hey, @botex98. We want the selector to catch all links that are in articles or general text, but not in the footer for example. 
The idea is for these links to mostly appear in long texts, where it is harder to spot them as links immediately. That's why the selector focuses on `p`, `span` and `.box`.

If you just want to start working on this, try implementing the mentioned cases first and then look for things that seems broken.

I am not sure about links on company pages like this one: https://www.datenanfragen.de/company/1and1-gb/
Maybe this is a topic of discussion, what do you think, @baltpeter?

**Comment by baltpeter** [comment]
Considering the links in the "box" are also styled, I think it's best to also style the ones on the company page.

**Comment by botex98** [comment]
@baltpeter let me know what do you think about these modifications. :)

**Comment by baltpeter** [comment]
@botex98 Changes look good on first glance, I've assigned @zner0L for the review as he wrote the original selector.

By the way: Not sure if you have seen it yet, but we are offering some additional [Hacktoberfest rewards](https://www.datarequests.org/blog/hacktoberfest-2020). Feel free to signup for that if you want. :)
