### ISSUE TITLE
Placeholder for related companies in the dev build

### ISSUE THREAD

**Issue by mal-tee** [datenanfragen/website#367]
Atm the company pages do not contain related companies in dev build. I think we should add placeholders.

**Comment by chrysillala** [comment]
Hi, I would like to work on this issue. Could you please assign and guide me? Thanks!

**Comment by baltpeter** [comment]
Sure, @chrysillala!

The companies in our company database list related companies on their detail pages. Take a look at [this company](https://www.datarequests.org/company/adux/) for example:

![image](https://user-images.githubusercontent.com/4048809/95678149-53a3d300-0bba-11eb-839a-532e032a0ea3.png)

The code for that is defined here:

https://github.com/datenanfragen/website/blob/05133ee1ee4d147c1cf643cde8161291e300332c/layouts/company/single.html#L106-L132

This is using Hugo templates (see [here](https://gohugo.io/templates/introduction/) for an introduction if you are not familiar with them). As you can see, the related companies are not shown if the site is run in dev mode:

https://github.com/datenanfragen/website/blob/05133ee1ee4d147c1cf643cde8161291e300332c/layouts/company/single.html#L106

That's because calculating the related companies is fairly resource-intensive and would thus slow down the dev build quite significantly.

However, instead of not showing anything in the dev build, we want to show placeholder related companies that don't require any computing.

**Comment by chrysillala** [comment]
Hi @baltpeter, thank you so much for the detailed explanation. 

Anyway, I'm having difficulties when running `hugo server` on my machine, even though there's no problem with `./deploy.sh` and `yarn dev`. 

Below the error message screenshot:
![image](https://user-images.githubusercontent.com/4686015/95680281-aa34ff80-0c02-11eb-90b2-6317abc3a9c4.png)

Would really appreciate if you could help me :)
Thanks!

**Comment by baltpeter** [comment]
To be honest, I have never seen that error before and don't really have any idea what might be causing it. Two ideas:

* Did you install the extended version of Hugo? Running `hugo version` should include `v0.xx.x/extended`.
* Which Hugo version are you on? It should be at least `v0.74.3` but later versions should also work (I'm on `v0.75.1`).
* Otherwise, you could try if the error also occurs in prod mode. For that, just run `hugo` (without the `server`).

**Comment by chrysillala** [comment]
@baltpeter : This is my Hugo version `Hugo Static Site Generator v0.76.3/extended darwin/amd64 BuildDate: unknown`
and this is what I got after running `hugo`, I'm not sure if this is the expected result..
![image](https://user-images.githubusercontent.com/4686015/95681713-aeb1e600-0c0b-11eb-9e12-0b93e0cafd67.png)

I think I'll just try to reclone the repo for now

**Comment by baltpeter** [comment]
The output from `hugo` is what we would expect. You should now have a full build of the site in the `public` folder. Worst case, you could work with that, I guess, but you would have to always build manually. :/ 

If recloning doesn't work, I am unfortunately out of ideas. You would have to ask on the Hugo forum.

**Comment by chrysillala** [comment]
Bad news, recloning didn't work, though I have the full build site and can see the compiled page with no styling.
However I already got the ideas on how to solve the issue. 
Please correct me if I'm wrong, 
By adding `else` statement before the end of `{{ if not .Site.Params.devMode }} ` and print the placeholder / dummy HTML inside. Is it the expected solution?

Thank you.

**Comment by baltpeter** [comment]
> Bad news, recloning didn't work, though I have the full build site and can see the compiled page with no styling.

That's unfortunate. The styling not loading is probably due to Hugo's default `baseURL` being `http://localhost:1313`. You could try overriding that but it's probably easiest to just start a PR. Netlify will then automatically build the changes and give you a preview.

> Is it the expected solution?

Yep, that should work. :)

**Comment by chrysillala** [comment]
Hi @baltpeter, kindly check my PR https://github.com/datenanfragen/website/pull/461
Thank you!
