### ISSUE TITLE
Web forms support

### ISSUE THREAD

**Issue by rugk** [datenanfragen/website#401]
In your talk at the [OKL Berlin](https://www.datenanfragen.de/verein/event/okl-berlin-05-2020/) (at the end around 35min) you have mentioned you would like to support web forms of companies…

Is there an issue tracking this idea yet? Is this idea still on your plan?
If not, then this shall be the issue… :stuck_out_tongue_winking_eye: 

---

So, technically, I think this is very hard, because usually these are cross-origin requests and due to the [same-origin policy](https://developer.mozilla.org/docs/Web/Security/Same-origin_policy) (SOP) these are not allowed. A website would have to [allow CORS requests](https://developer.mozilla.org/docs/Web/HTTP/CORS).

My idea to circumvent this would be a WebExtension (browser add-on), that can offer an API for this project and then submit the requests.

Another problem through maybe that the forms may change fast or even have special CSRF tokens against such things we try to do here… :thinking:

**Comment by baltpeter** [comment]
I could have sworn we had an issue for web form support already but you're right, there isn't one. Thanks for fixing that. :D 

I also agree with your assessment. I don't see a way to implement actually submitting the forms from our site. We would also have to implement a mapping between the form fields and the stuff we generate in our schema somehow which seems prohibitively hard. Also, there will be forms submitted via JS instead of a POST request which would have to be handled differently.

Personally, I was thinking of a simpler implementation, more like what I implemented in #308: We would link the user to the web form and offer them to copy the text manually. Given that there really aren't that many companies where sending via email is not a (good) option, this seems like a sensible compromise to me.
