### ISSUE TITLE
No Cookies Popup

### ISSUE THREAD

**Issue by davenewham** [datenanfragen/website#430]
The cookie settings is hidden under a menu which I wasn't even aware of when I first visited the site. 

https://gdpr.eu/cookies/
Via the gdpr directive it seems you must have explicit consent _before_ using any cookies except for "strictly necessary" cookies. This could be done with a popup on first visit.

**Comment by baltpeter** [comment]
Thanks for bringing this up. We have very deliberately opted not to have a cookie popup. We are not fans of cookie popups (they are annoying and provide little actual use to the user). One of our core philosophies is to design our sites in the most privacy-friendly way possible, mostly through data minimization meaning that we don't actually process any personal data unless absolutely necessary. As a result, we are of the opinion that our current implementation is in line with the relevant legislation. Nevertheless, we actually do have some changes planned to improve this aspect even more.

Let me elaborate. Note that this is our interpretation of the law. We are however not lawyers and cannot give legal advice.

The GDPR is actually not relevant in this case, it doesn't care about cookies, only personal data (see [our blog post](https://www.datarequests.org/blog/gdpr-cheat-sheet/) or Art. 4 GDPR for exact definitions of these terms) that is processed by a controller (which would be us in this case). In our case, we have made sure that we never even receive any of the data saved in the cookies, so we cannot process it.

The legislation that is actually relevant has the very compact name of ["Directive 2009/136/EC of the European Parliament and of the Council of 25 November 2009 amending Directive 2002/22/EC on universal service and users’ rights relating to electronic communications networks and services, Directive 2002/58/EC concerning the processing of personal data and the protection of privacy in the electronic communications sector and Regulation (EC) No 2006/2004 on cooperation between national authorities responsible for the enforcement of consumer protection laws"](https://eur-lex.europa.eu/eli/dir/2009/136/oj) (and is thus usually just called the "cookie directive". In particular, we are interested in this provision:

> Member States shall ensure that the storing of information, or the gaining of access to information already stored, in the terminal equipment of a subscriber or user is only allowed on condition that the subscriber or user concerned has given his or her consent, having been provided with clear and comprehensive information, in accordance with Directive 95/46/EC, inter alia, about the purposes of the processing. This shall not prevent any technical storage or access for the sole purpose of carrying out the transmission of a communication over an electronic communications network, or as strictly necessary in order for the provider of an information society service explicitly requested by the subscriber or user to provide the service.

This is where the "strictly necessary" is coming from. In order to interpret that, we can look at [this working paper by the Article 29 working group](https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2012/wp194_en.pdf). Chapter 3 lists various use cases that can be classified as "strictly necessary". Of interest to us are "user-input cookies" ("typically used to keep track of the user’s input when filling online forms over several pages"), "UI customization cookies" ("used to store a user’s preference regarding a service across web pages") and "result display preference cookies" (used to remember the user’s preference regarding online search queries).

In terms of actual cookies, there are actually only two that are set automatically: `country` and `changed_saved_companies`. All other cookies are only set after the user has interacted with a relevant control.  
We have concluded that the `country` cookie is strictly necessary for our website. It is filled with a best guess when the user first enters the website. As the country determines the companies the user sees (among other things), it is very important to be consistent here. Without a cookie saving this information, we wouldn't be able to ensure that the user always sees the same companies.  
As for the `changed_saved_companies` cookie, legally speaking we think that it also falls under the "strictly necessary" definition. However, we have determined that we can also implement the wizard on the homepage in a way that only sets a cookie once the user has changed something. This is a change we plan to implement.

We also save some data in local storage (one of the local storage APIs anyway, as we are using [localForage](https://localforage.github.io/localForage/)). I won't go into detail on that here but we have of course also evaluated the necessity of those individual cases and have determined that our use is OK here. However, we also want to improve even more and limit data storage where possible.

Here are also some additional references that we considered (sorry, these are only available in German as they are in relation to a recent German court case on this topic): [1](https://www.bundesgerichtshof.de/SharedDocs/Pressemitteilungen/DE/2020/2020067.html?nn=10690868), [2](https://diercks-digital-recht.de/2019/10/zum-eugh-urteil-planet49-az-c-673-17-benoetigen-cookies-ab-jetzt-immer-einer-einwilligung-spoiler-nein/), [3](https://diercks-digital-recht.de/2020/05/eine-erste-einordnung-des-bgh-urteils-cookie-ii-i-zr-7-16-voreingestellte-einwilligungen-opt-outs-sind-unwirksam-und-das-gilt-grundsaetzlich-auch-fuer-cookies/)

Finally, regarding our [privacy controls](https://www.datarequests.org/privacy-controls): These actually don't (primarily) deal with cookies. They allow you to enable and disable certain features of the website that sometimes require the use of local storage. For each of them, we have evaluated whether it is appropriate to enable them by default. For the current privacy controls, we concluded that they are all "safe" and "private" enough as (apart from the search) they all work solely in the user's browser and never transmit any data to us (and of course, the search feature doesn't save any data either). Personally, I honestly see little reason to disable any of our current privacy controls but we have still decided to provide that ability out of principle.

As I have said, we don't believe in big popups that interrupt the flow (and that most users just accept anyway without reading). Instead, we have tried to incorporate links to the privacy controls when the user actually comes into contact with the relevant features. For example, take a look at the "entertainment" tab of the wizard on the homepage or the "My saved data" page.

I hope this explains our considerations of this topic. Sorry for the long wall of text but this is a complex topic that we have put a lot of thought into (after all, that is sort of what we do :D). We do of course welcome any input on how we can improve. Let us know what you think.
