### ISSUE TITLE
Wizard: Can fetch 404 error be suppressed?

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#434]
The wizard on our homepage loads the suggested companies from a URL of the form: `https://<domain>/db/suggested-companies/<country_code>_wizard.json`

If we don't have suggested companies for a country (currently, we only have them for DE, AT and UK), this request fails with a 404 error. This behaviour is expected and handled in the code (in this case, we just don't show any suggested companies).

However, browsers still show an error message in the console. To reproduce this, visit the homepage and set the country to `all`. Notice the following error in the browser console:

![image](https://user-images.githubusercontent.com/4048809/95655234-5983b080-0af5-11eb-9b90-d7e774ec8fa8.png)

Can this error be suppressed? I didn't find a way from a quick look at MDN but I may well have missed something. It is however also possible that this cannot be fixed.

This is the relevant code:

https://github.com/datenanfragen/website/blob/05133ee1ee4d147c1cf643cde8161291e300332c/src/Components/Wizard.js#L62-L79

**Comment by rgroves** [comment]
I believe that there is no way to prevent the 404 from being logged by the browser when the request is made client side.

Might I suggest, what I think is the easiest way to handle this, just create files for all 2-digit country codes with an empty array within `datenanfragen/data/suggested-companies`. 

Alternatively, but adding more complexity than you probably want, you can create a tiny service that you host somewhere that just accepts the URL and does the fetch on behalf of your static site. The `fetch` being done in the relevant code would change to call your service passing `url` as a parameter and the service would reply with the data if it exists or an empty object if it does not. Since the externally hosted service is doing the fetch the browser never sees the 404.

If you'd like me to implement either of those solutions, please let me know. For the former, I would need to know what country codes you're using (assuming something like [ISO 3166](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)). For the latter, that would probably be a longer discussion of how you'd want to implement it (like a small node process that just responds to a GET request on a certain endpoint) and what other concerns would need to be handled (CORS, throttling, security/api key, etc.). As I mentioned, this route would be adding more complexity than it's worth, but I mention it as a possibility.

**Comment by baltpeter** [comment]
Thanks for looking into this, @rgroves!

I like the idea of having stubs for the missing countries. However, I would prefer not having them in the `data` repo as that would make it pretty hard to grasp what countries we still need to work on. Instead, I would propose doing that in the `website` deploy script. We are already doing a fair bit of post-processing on the `data` repo there, so that would make sense imo.

You could either implement that in the [bash](https://github.com/datenanfragen/website/blob/master/deploy.sh) or [Node](https://github.com/datenanfragen/website/blob/master/prepare-deploy.js) script.

> I would need to know what country codes you're using (assuming something like ISO 3166).

We are indeed using ISO 3166-1 alpha-2. In fact, our schema defines the full list of allowed countries:

https://github.com/datenanfragen/data/blob/ebafa9999cf74c02d3591ef602d72564d1687d70/schema.json#L21

If you go the Node route, you could even `require()` the schema and access that array directly.

**Comment by rgroves** [comment]
Sounds like the Node route is best so the existing schema can be leveraged.  I will work on this and submit a PR in the next day or two.

**Comment by rgroves** [comment]
I noticed the "all" selection isn't currently accounted for. Would you like me to make a stub file for the "all" selection? I'm assuming that the wizard_all.json file would contain an object with all of the key value pairs from the other existing (non-stubbed) country files. Or would that be considered a separate issue?

**Comment by baltpeter** [comment]
Ah, sorry for not being more clear about "all". "all" should not aggregate the companies from the other countries (it would hold those companies that are relevant for all countries, currently we don't have any such company). For the purposes of this issue, you can treat it like any real country and just fallback to an empty array.
