### ISSUE TITLE
Croatian translation

### ISSUE THREAD

**Issue by milotype** [datenanfragen/website#566]
I'd like to add my Croatian translation on Weblate. I've translated it localy up to 98%, but I cannot upload the .po file on Weblate. Curretnly it's only possible to download files, but not to upload ... So please:

- enable file uploading on Weblate, or 
- if you don't want that, please add my attached file below.

Also, please add new source strings for **Croatian** language, similar to:
`msgctxt "i18n-widget.language-desc-de"` and `msgctxt "hugo.de"`

[datenanfragen-de-website-hr.po.zip](https://github.com/datenanfragen/website/files/6296878/datenanfragen-de-website-hr.po.zip)

**Comment by baltpeter** [comment]
Wow, thank you very much for the translations!

I couldn't find an option to enable file uploads for everyone in Weblate but I have manually uploaded the file myself. If you want, I can invite you as a contributor to the project on Weblate. I think you should be able to do file uploads yourself then.

Since you have already basically translated everything, we can almost get the new language version up. There's only two things that are missing and that we cannot do ourselves:

* We need to find a website/domain name.  
  For reference, these are the names of the existing language versions (since .hr domains unfortunately seem to be prohibitively expensive, we'll have to go with .org for the Croatian domain as well…):
  - Datenanfragen.de (German)
  - datarequests.org (English)
  - demandetesdonnees.fr (French)
  - pedidodedados.org (Portuguese)
  - solicituddedatos.es (Spanish)
* The request templates need to be translated. Those are simply plain text files (with some minor custom markup) in this folder: https://github.com/datenanfragen/data/tree/master/templates  
  Only the templates in the `en` folder need to be translated, any additional templates are specific to particular countries/languages and don't need to be translated.

If you want to help with those two things as well, that would be hugely appreciated of course.

> Also, please add new source strings for Croatian language, similar to:
> msgctxt "i18n-widget.language-desc-de" and msgctxt "hugo.de"

Yep, I'll do that once the tests in #567 have finished and I can merge that PR.

**Comment by milotype** [comment]
Yes, if you like, you can invite me as a contributor to the project on Weblate.

I'm just a translator, not a programmer … I can't really help with the issue about the domain name.

I will work on translating request templates and send them via GitHub. (Ideally, you should make them translatable via Weblate as well – depending on time and possible costs ;-) )

Whatever you have done in #568 about _language desc_, currently there is no option to select Croatian :-( But maybe it just hasn't been updated until now.

**Comment by baltpeter** [comment]
> Yes, if you like, you can invite me as a contributor to the project on Weblate.

Done. :)

> I'm just a translator, not a programmer … I can't really help with the issue about the domain name.

Sorry, I was a little unclear there. We'll take care of the technical stuff for the domain but as none of us speak any Croatian, we cannot come up with a name. We need a translation of "datarequests" (or similar) into Croatian that makes for a good name.

> I will work on translating request templates and send them via GitHub. (Ideally, you should make them translatable via Weblate as well – depending on time and possible costs ;-) )

Awesome, thank you!

Yeah, it would be great to have everything (including the templates and blog posts) in Weblate but from our understanding, Weblate is only meant for short sentences, not whole documents. :/

> Whatever you have done in #568 about _language desc_, currently there is no option to select Croatian :-( But maybe it just hasn't been updated until now.

I have already added the translation there (according to my dictionary, it's "Hrvatski" for "Croatian"). But as the pull requests is not merged yet, this won't appear in Weblate yet.

**Comment by milotype** [comment]
Thanx! I can now upload translation files!

Suggestion for Croatian translation for the Croatian domain name for "datarequests.org" = "**osobnipodaci.org**" (osobni podaci = personal data). If somebody has a alternate/better suggestion, I don't mind ...

> ... from our understanding, Weblate is only meant for short sentences, not whole documents. :/

I'm not sure about long source strings, but I think it is possible to separate whole documents into separate paragraphs/strings ...

> But as the pull requests is not merged yet, this won't appear in Weblate yet.

OK, so we have to wait ...

**Comment by baltpeter** [comment]
> Suggestion for Croatian translation for the Croatian domain name for "datarequests.org" = "osobnipodaci.org" (osobni podaci = personal data). If somebody has a alternate/better suggestion, I don't mind ...

Thanks for the suggestion. Is there a word like "data request" in Croatian? If so, I think that would be better for consistency as all other names hint at the notion of requesting your personal data.

> I'm not sure about long source strings, but I think it is possible to separate whole documents into separate paragraphs/strings ...

True, that might be an option. Unfortunately, that would require quite a few changes on our end, though, so it probably won't happen too soon.

**Comment by milotype** [comment]
IMO: **osobnipodaci** actually does imply access to/changing _personal data_ ... ;-) As you probably know, _literal_ translation isn't always the best way to go … Also, **osobnipodaci** is the shortest domain name, comparing to the alternative names:

Alternatives:
- zahtijevanjepodataka (requestingdata, umbiguous, because it means _any_ data)
- zahtijevanjeosobnihpodataka (requestingpersonaldata, way too long domain name)

About Translated string length:
https://docs.weblate.org/en/latest/user/translating.html#translated-string-length

Cheers,
Milo

**Comment by baltpeter** [comment]
Ah, I see. Thanks for clearing that up. In that case, we also think that's a good name and we've registered the domain. :)

I have also prepared a preview of the Croatian site in #568 which you can see here: https://deploy-preview-568--datenanfragen.netlify.app/hr  
Note: The links in the header direct you to the English site. That is a known bug that only occurs in the deploy preview and will not happen on the published site.

As far as I can see, with that the Croatian site is pretty much ready for merge, we're only missing two things now:

* the request templates
* The string 'cdb-categories' currently has plural forms for 'one' and 'other'. But Hugo is complaining that we also need 'few'. Probably because that's not a thing in any of the languages we have currently?  
  Not sure if you can add that through Weblate, but if you simply tell me the translation, I can also add it manually.

**Comment by milotype** [comment]
@baltpeter Thank you for the Croatian preview!

> request templates

I'm still in the process of translating them ... will take a while ;-(

> The string 'cdb-categories' currently has plural forms for 'one' and 'other'

Yes, Croatian needs 3 plural forms. Both plural forms should translate into **Kategorije:**

And ideally, there would be only one key (something like "hugo.cdb-categories") containing the necessary plural forms, depending upon the language being translated. But I'm no programmer. Sorry I can't help implementing it.

**Comment by baltpeter** [comment]
> I'm still in the process of translating them ... will take a while ;-(

I was gonna say that there's no need to hurry but you've already submitted the PR. :D Huge thanks!

> Yes, Croatian needs 3 plural forms. Both plural forms should translate into **Kategorije:**

Good to know. I have added the translation.

> And ideally, there would be only one key (something like "hugo.cdb-categories") containing the necessary plural forms, depending upon the language being translated.

Yes, that's exactly how it's implemented in our translation files. But I'm not sure if Weblate supports adding new plural forms through the interface.

---

I have now updated the deploy preview with the latest changes and the templates. With that, we are pretty much ready to launch the new site.

There's just one thing missing: For technical reasons, we need at least one blog post. Luckily, we can 'recycle' the templates you already translated for this and publish them as stub blog posts with sample letters ([here's](https://www.demandetesdonnees.fr/blog/modele-lettre-rgpd-acces/) an example from the French site).

I can create those posts but I need translations for the post titles:

* Sample letter for requests for access to personal data as per Art. 15 GDPR
* Sample letter for rectification requests as per Art. 16 GDPR
* Sample letter for erasure requests as per Art. 17 GDPR (“right to be forgotten”)
* Sample letter for objections against direct marketing as per Art. 21(2) GDPR

**Comment by milotype** [comment]
> I can create those posts but I need translations for the post titles:

>     * Sample letter for requests for access to personal data as per Art. 15 GDPR
Uzorak pisma za zahtjeve za pristup osobnim podacima prema čl. 15. GDPR-a

>     * Sample letter for rectification requests as per Art. 16 GDPR
Uzorak pisma za zahtjeve za ispravak prema čl. 16. GDPR-a

>     * Sample letter for erasure requests as per Art. 17 GDPR (“right to be forgotten”)
Uzorak pisma za zahtjeve za brisanje prema čl. 17 GDPR („pravo na zaborav”)

>     * Sample letter for objections against direct marketing as per Art. 21(2) GDPR
Uzorak pisma za prigovore protiv izravnog marketinga prema čl. 21 (2) GDPR-a
