### ISSUE TITLE
Change of country

### ISSUE THREAD

**Issue by WebworkrNet** [datenanfragen/website#681]
According to #677, companies are displayed depending on the preselected country.

**Steps to reproduce**

1. Initial situation: `Austria` is selected.
2. Search for `Rundfunk`.

**Expected behaviour**
Only Austrian entries should be displayed.
**Actual behaviour**
In fact, the German `NDR`, `RBB` and `WDR` are also displayed. 

I have checked all 3 entries. Only `Germany` is stored in all data records.

**Comment by mal-tee** [comment]
https://github.com/datenanfragen/website/blob/6aa8e63aed2bd73d621b02304a95ed55d1a65f12/src/Components/SearchBar.js#L36-L41

**Comment by mal-tee** [comment]
Seems like this is known and wanted behavior.

**Comment by zner0L** [comment]
Yes, this is wanted behavior, since German companies regularly process data from Austrian or Swiss citizens, but this is not generally true the other way around. While it is true that it would be much better to solve this by listing Switzerland and Austria in the company record where relevant, we use this workaround because it is really hard to determine exactly in what countries a company is operating.

**Comment by WebworkrNet** [comment]
OK, thank you both for the explanations.
