### ISSUE TITLE
Generator: More logical order for the request parameters

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/website#82]
The transport medium should really come before the recipient address input.

In addition, the address input should be changed to an email address input if 'email' is selected. We might also want to consider still showing the address in the company widget.

**Comment by xeluna** [comment]
I'd like to work on this.

To clarify, what needs to be done is:
- Change the order so that transport medium comes before recipient address
- If transport medium is email, the textarea should be replaced with an input, filled with the recipient's email address (if there is one)
- Add the physical address to the company widget, which currently doesn't have this information?

**Comment by baltpeter** [comment]
Great, thank you!

> To clarify, what needs to be done is: […]

Looks good to me.

Just one note: The physical address in the company widget should probably be comma-separated instead of new-line-separated as it usually is.

**Comment by xeluna** [comment]
Thank you for clarifying. I noticed that the `data-portability` checkbox would now be below the address if the 2 elements (transport medium & address input) are swapped. 

Should the checkbox also be moved such that it is directly below the transport medium and above the address input?

I'm checking because changing the transport medium also has an effect on the checkbox, and it so happens that on my screen resolution, if I'm changing from email -> fax/letter, the 4 rows textarea pushes the checkbox below the fold, so I do not notice the change in state as it happens off the screen.

**Comment by baltpeter** [comment]
I agree that unintentionally hiding the checkbox like that isn't great. However, I also think this option isn't that important (most companies ignore it anyway…). As it is more of an 'advanced user option', personally I would keep it where it is.

What do you think, @zner0L?

**Comment by xeluna** [comment]
Sounds good. :) I've opened the PR as it is for now.

**Comment by zner0L** [comment]
Closed by #126
