### ISSUE TITLE
JS error (undefined)

### ISSUE THREAD

**Issue by GloomyD** [datenanfragen/website#882]
[S'il y a lieu, pense à fournir le contexte de l'erreur, c.-à-d. décrire ce que tu as fait avant que l'erreur ne se produise. Pense également à supprimer toute information sensible des informations de débogage ci-dessous.]

**Debug information:**

```js
{
    "type": "unhandledrejection",
    "error": {
        "message": "Error response received for message <get-frame-manager-configuration>",
        "name": "Error",
        "stack": "@safari-web-extension://B0E29931-E034-4FB6-9602-AE7FAB61817E/inline/injected.js:4:98435"
    },
    "defaultPrevented": false,
    "eventPhase": 2,
    "isTrusted": false,
    "returnValue": true,
    "code_version": "1.0.0",
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15",
    "url": {
        "href": "https://www.demandetesdonnees.fr/",
        "protocol": "https:",
        "host": "www.demandetesdonnees.fr",
        "hostname": "www.demandetesdonnees.fr",
        "port": "",
        "pathname": "/",
        "search": "",
        "hash": "",
        "origin": "https://www.demandetesdonnees.fr",
        "ancestorOrigins": {}
    }
}
```

**Comment by baltpeter** [comment]
Hi, thanks for the report!

This is actually not a problem with our site but an error in one of the extensions you have installed. We do have code that is supposed to filter these unnecessary errors out, but it seems like Safari has changed the scheme they are using, which is why it slipped through.

I've opened a PR (#886) to handle the new scheme. Once that's merged, the error should not show up anymore.
